### PR TITLE
Update Abine name and link (issue #74)

### PR DESCRIPTION
**Pull request by SebastianZimmeck**

### CODE REVIEW

**Comment by dharb** [comment]
@SebastianZimmeck do we want to update all references to Abine? There are a few others around the site.

**Comment by SebastianZimmeck** [comment]
> @SebastianZimmeck do we want to update all references to Abine? There are a few others around the site.

Good point, @dharb! Yes, updating all makes sense to me.

**Comment by dharb** [comment]
Cool, I'm happy to do so and push to this branch if you'd like.

**Comment by SebastianZimmeck** [comment]
> Cool, I'm happy to do so and push to this branch if you'd like.

That would be perfect if you could do so, @dharb!

**Review by dharb — APPROVED** [review]

**Comment by SebastianZimmeck** [comment]
OK, this looks good to me!

**Pull request merged**
