### PR TITLE
Carousel v2

### PR DESCRIPTION
**Pull request by dknopf**
This contains a finished version of the testimonials carousel, with all the content added in the requisite markdown file.

### CODE REVIEW

**Comment by sballesteros** [comment]
Thanks for the email @asoltani. @dknopf sorry for the delay, I had totally missed the GH notification.
Would it be possible to merge https://github.com/globalprivacycontrol/landing-page/pull/20 before we review/merge this one (https://github.com/globalprivacycontrol/landing-page/pull/21)?
I had asked Dave to review https://github.com/globalprivacycontrol/landing-page/pull/20 but I think that he is currently not feeling well. @dknopf any chance that you could review https://github.com/globalprivacycontrol/landing-page/pull/20 instead? I can then switch to reviewing/merging this PR (I may have to fix some minor conflicts).
Thanks!

**Comment by SebastianZimmeck** [comment]
@dknopf, has moved to other projects (especially, as one of the main organizers of [WesHack](https://www.weshack.org/) this weekend). So, @dknopf, it would certainly be great if you can review this, but definitely do not feel obligated. We can find another solution.

**Comment by dknopf** [comment]
Yeah, I unfortunately will not be able to review the previous merge, I think it best if someone else take a look at it!

**Comment by asoltani** [comment]
@dknopf no problem, and thank you so much for your hard work.  we'll do our best to manage.

@sballesteros do you want to go ahead and merge these changes?  i'm happy to do it but unfortnately wouldn't know how to fix things if anything breaks as a result.

**Comment by sballesteros** [comment]
> @sballesteros do you want to go ahead and merge these changes? i'm happy to do it but unfortnately wouldn't know how to fix things if anything breaks as a result.

Yep happy to (I will have time tonight (Pacific Time))! That being said I can't currently do it as at least 1 approving review is required for https://github.com/globalprivacycontrol/landing-page/pull/20. 

@asoltani Could you bump my GitHub permissions so that I have merge privileges?

**Comment by asoltani** [comment]
Thanks @sballesteros <https://github.com/sballesteros> — I just bumped you
to maintainer (let me know if that works)

**Comment by sballesteros** [comment]
Thanks @asoltani, unfortunately `maintainer` is not enough to have the permission to:

>  "Merge pull requests on protected branches, even if there are no approving reviews" 

and I would need to be `admin` (see [docs](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization))

Screen Shot 2021-04-21 at 8 52 37 AM

**Comment by asoltani** [comment]
Oops sorry.  Just bumped you to Admin

**Comment by sballesteros** [comment]
Awesome thanks! I am all set now and will merge the PRs at the end of the day (Pacific Time).

**Comment by sballesteros** [comment]
Closing in favor of https://github.com/globalprivacycontrol/landing-page/pull/23 which is pretty much this PR rebased against the latest `main` and with conflict resolved.

**Comment by asoltani** [comment]
@sballesteros thanks so much for knocking these out!

**Pull request closed without merging**
